steps:
  - label: ":docker: Build"
    command: Start-Process .\scripts\build.ps1
  - wait
  - label: ":docker: Test"
    command: Start-Process .\scripts\test.ps1
  - wait
  - label: ":docker: Deploy"
    command: Start-Process .\scripts\deploy.ps1