steps:
  - label: ":docker: Build"
    command: .\scripts\build.bat
  - wait
  - label: ":docker: Test"
    command: .\scripts\test.bat
  - wait
  - label: ":docker: Deploy"
    command: .\scripts\deploy.bat